feat(#130): create events list
StudyDistractor/sdp pull request #142
Opened 2023-05-16 17:20 UTC by lipefree

Implements #130 and changes the UI a lot to follow to Android colors and components.

2023-05-16 20:59 UTC, lipefree commented
> It's a great PR imo! Is there a reason why the "join" button is not working though? You shouldn't see a join button on an event you joined, you should rather either see "withdraw" or nothing imo

Yeah I was planning to merge last so that I can link everything, it will be working when the PR is merged

2023-05-17 09:36 UTC, bluedrack requested changes
The pr is good but it will cause a lot of conflict. You probably would have had a better time doing two instead of one to minimize the damage.

2023-05-17 09:36 UTC, bluedrack commented on app/src/main/java/com/github/studydistractor/sdp/eventList/EventListModel.kt
> +    fun getAllEvents(): List<Event>
Comment the model at least

2023-05-17 09:36 UTC, bluedrack commented on app/src/main/java/com/github/studydistractor/sdp/ui/DailyChallengeScreen.kt
>  import androidx.compose.material.MaterialTheme
Update material to material 3 no ?

2023-05-17 09:36 UTC, bluedrack commented on app/src/main/java/com/github/studydistractor/sdp/ui/components/ListedEvent.kt
> +                modifier = Modifier.testTag("event-list-screen__event-name")
use unique tag for testing like adding event id or something.

2023-05-17 13:12 UTC, lipefree commented on app/src/main/java/com/github/studydistractor/sdp/eventList/EventListServiceFirebase.kt
> +    override fun getAllEvents(): List<Event> {
I think it is better to not live update the list, for example when the user is scrolling, you don't want to have a changing list.

2023-05-17 13:27 UTC, AthenaPK requested changes
Looking good! One comment on the functionality: I think we should only display events that are currently ongoing or are scheduled in the future, it doesn't make sense to include events that happened in the past in the list.

2023-05-17 13:48 UTC, lipefree commented
> Looking good! One comment on the functionality: I think we should only display events that are currently ongoing or are scheduled in the future, it doesn't make sense to include events that happened in the past in the list.

The thing is that we made a mistake when implementing the format for dates, but I will look into it before merging

2023-05-17 13:49 UTC, bluedrack commented on app/src/main/java/com/github/studydistractor/sdp/eventList/EventListServiceFirebase.kt
> +    override fun getAllEvents(): List<Event> {
I hadn't seen it that way thanks for clarifying my view of the code!

2023-05-20 13:54 UTC, aizensoosuke approved these changes
LGTM, thanks a lot for all the work :)

2023-05-20 15:14 UTC, abouquet27 approved these changes
LGTM

2023-05-20 15:15 UTC, merged