Fix! : Adding test and refactor #40
StudyDistractor/sdp pull request #54
Opened 2023-03-28 13:21 UTC by bluedrack

the code to achieves the 80 pour-cent code coverage. Adding packages to clean up the code base.

2023-03-28 16:32 UTC, lipefree requested changes
Overall efficient code, the repackaging is nice ! But include some class and function documentation in stuff you wrote in this PR.

2023-03-28 16:32 UTC, lipefree commented on app/src/main/java/com/github/studydistractor/sdp/register/RegisterAuthModule.kt
> +//    @Provides
Remove comment

2023-03-29 07:41 UTC, abouquet27 reviewed
This commit is a mix of refactoring, adding tests and modifications in the register class. The description of the commit should be more explicit and must list precisely all the major modifications because we cannot understand what is going on, specially if we are working on those files too

2023-03-29 08:06 UTC, bluedrack commented
> This commit is a mix of refactoring, adding tests and modifications in the register class. The description of the commit should be more explicit and must list precisely all the major modifications because we cannot understand what is going on, specially if we are working on those files too



> This commit is a mix of refactoring, adding tests and modifications in the register class. The description of the commit should be more explicit and must list precisely all the major modifications because we cannot understand what is going on, specially if we are working on those files too

Yes I agree with you but I need to do that to implement the hilt implementation so it is necessary to add Module and Interface so that the testing will be more easy later.

2023-03-29 08:48 UTC, abouquet27 requested changes
Great modularisation of the code and it is a better structural tree. The project is more clearer and the tests are good. 

Apart from the comment I posted earlier, it is fine for me
LGTM

2023-03-29 09:01 UTC, lipefree approved these changes
LGTM now !

2023-03-29 09:06 UTC, merged